export const menuItems = [
  {label: 'MATCHES', link: '/'},
  {label: 'TABLE', link: '/tables'},
  {label: 'STATS', link: '/stats'},
  {label: 'PLAYERS', link: '/players'},
];

export const teams: { [key: string]: string } = {
  "liverpool": "Liverpool",
  "arsenal": "Arsenal",
  "aston_villa": "Aston Villa",
  "bournemouth": "Bournemouth",
  "brentford": "Brentford",
  "brighton": "Brighton",
  "burnley": "Burnley",
  "chelsea": "Chelsea",
  "crystal_palace": "Crystal Palace",
  "everton": "Everton",
  "fulham": "Fulham",
  "leeds": "Leeds",
  "man_city": "Man City",
  "man_utd": "Man Utd",
  "newcastle": "Newcastle",
  "nottm_forest": "Nott'm Forest",
  "spurs": "Spurs",
  "sunderland": "Sunderland",
  "west_ham": "West Ham",
  "wolves": "Wolves",
};

export const teamLogo: { [key: string]: [string, string] } = {
  "Liverpool": ['liverpool', 'liverpool.png'],
  "Arsenal": ['arsenal', 'premier-league.png'],
  "Aston Villa": ['aston_villa', 'premier-league.png'],
  "Bournemouth": ['bournemouth', 'bournemouth.png'],
  "Brentford": ['brentford', 'premier-league.png'],
  "Brighton": ['brighton', 'premier-league.png'],
  "Burnley": ['burnley', 'premier-league.png'],
  "Chelsea": ['chelsea', 'premier-league.png'],
  "Crystal Palace": ['crystal_palace', 'premier-league.png'],
  "Everton": ['everton', 'premier-league.png'],
  "Fulham": ['fulham', 'premier-league.png'],
  "Leeds": ['leeds', 'premier-league.png'],
  "Man City": ['man_city', 'premier-league.png'],
  "Man Utd": ['man_utd', 'premier-league.png'],
  "Newcastle": ['newcastle', 'premier-league.png'],
  "Nott'm Forest": ['nottm_forest', 'premier-league.png'],
  "Spurs": ['spurs', 'premier-league.png'],
  "Sunderland": ['sunderland', 'premier-league.png'],
  "West Ham": ['west_ham', 'premier-league.png'],
  "Wolves": ['wolves', 'premier-league.png'],
};